import type {
  ApplicationTask,
  AppSettings,
  Job,
  PipelineRun,
  ResumeProjectCatalogItem,
  StageEvent,
} from "../types";

export const createJob = (overrides: Partial<Job> = {}): Job => ({
  id: "job-1",
  source: "linkedin",
  sourceJobId: null,
  jobUrlDirect: null,
  datePosted: null,
  title: "Backend Engineer",
  employer: "Acme Labs",
  employerUrl: null,
  jobUrl: "https://example.com/job-1",
  applicationLink: "https://example.com/apply",
  disciplines: null,
  deadline: null,
  salary: null,
  location: "California",
  degreeRequired: null,
  starting: null,
  jobDescription: "Job description content",
  status: "ready",
  outcome: null,
  closedAt: null,
  suitabilityScore: 90,
  suitabilityReason: "Strong fit",
  tailoredSummary: null,
  tailoredHeadline: null,
  tailoredSkills: null,
  selectedProjectIds: null,
  pdfPath: null,
  tracerLinksEnabled: false,
  sponsorMatchScore: null,
  sponsorMatchNames: null,
  jobType: null,
  salarySource: null,
  salaryInterval: null,
  salaryMinAmount: null,
  salaryMaxAmount: null,
  salaryCurrency: null,
  isRemote: null,
  jobLevel: null,
  jobFunction: null,
  listingType: null,
  emails: null,
  companyIndustry: null,
  companyLogo: null,
  companyUrlDirect: null,
  companyAddresses: null,
  companyNumEmployees: null,
  companyRevenue: null,
  companyDescription: null,
  skills: null,
  experienceRange: null,
  companyRating: null,
  companyReviewsCount: null,
  vacancyCount: null,
  workFromHomeType: null,
  discoveredAt: "2025-01-01T00:00:00Z",
  processedAt: null,
  appliedAt: null,
  createdAt: "2025-01-01T00:00:00Z",
  updatedAt: "2025-01-01T00:00:00Z",
  ...overrides,
});

export const createStageEvent = (
  overrides: Partial<StageEvent> = {},
): StageEvent => ({
  id: "event-1",
  applicationId: "job-1",
  title: "Moved to applied",
  groupId: null,
  fromStage: null,
  toStage: "applied",
  occurredAt: Date.now(),
  metadata: null,
  outcome: null,
  ...overrides,
});

export const createApplicationTask = (
  overrides: Partial<ApplicationTask> = {},
): ApplicationTask => ({
  id: "task-1",
  applicationId: "job-1",
  type: "todo",
  title: "Follow up",
  dueDate: null,
  isCompleted: false,
  notes: null,
  ...overrides,
});

export const createPipelineRun = (
  overrides: Partial<PipelineRun> = {},
): PipelineRun => ({
  id: "run-1",
  startedAt: "2025-01-01T00:00:00Z",
  completedAt: null,
  status: "running",
  jobsDiscovered: 0,
  jobsProcessed: 0,
  errorMessage: null,
  ...overrides,
});

export const createResumeProjectCatalogItem = (
  overrides: Partial<ResumeProjectCatalogItem> = {},
): ResumeProjectCatalogItem => ({
  id: "p1",
  name: "Project 1",
  description: "Description 1",
  date: "2024",
  isVisibleInBase: true,
  ...overrides,
});

export const createAppSettings = (
  overrides: Partial<AppSettings> = {},
): AppSettings => ({
  model: "gpt-4o",
  defaultModel: "gpt-4o",
  overrideModel: null,
  modelScorer: "gpt-4o",
  overrideModelScorer: null,
  modelTailoring: "gpt-4o",
  overrideModelTailoring: null,
  modelProjectSelection: "gpt-4o",
  overrideModelProjectSelection: null,
  llmProvider: "openai",
  defaultLlmProvider: "openai",
  overrideLlmProvider: null,
  llmBaseUrl: "https://api.openai.com/v1",
  defaultLlmBaseUrl: "https://api.openai.com/v1",
  overrideLlmBaseUrl: null,
  pipelineWebhookUrl: "",
  defaultPipelineWebhookUrl: "",
  overridePipelineWebhookUrl: null,
  jobCompleteWebhookUrl: "",
  defaultJobCompleteWebhookUrl: "",
  overrideJobCompleteWebhookUrl: null,
  profileProjects: [],
  resumeProjects: {
    maxProjects: 3,
    lockedProjectIds: [],
    aiSelectableProjectIds: [],
  },
  defaultResumeProjects: {
    maxProjects: 3,
    lockedProjectIds: [],
    aiSelectableProjectIds: [],
  },
  overrideResumeProjects: null,
  rxresumeBaseResumeId: null,
  ukvisajobsMaxJobs: 50,
  defaultUkvisajobsMaxJobs: 50,
  overrideUkvisajobsMaxJobs: null,
  adzunaMaxJobsPerTerm: 50,
  defaultAdzunaMaxJobsPerTerm: 50,
  overrideAdzunaMaxJobsPerTerm: null,
  gradcrackerMaxJobsPerTerm: 50,
  defaultGradcrackerMaxJobsPerTerm: 50,
  overrideGradcrackerMaxJobsPerTerm: null,
  searchTerms: ["Software Engineer"],
  defaultSearchTerms: ["Software Engineer"],
  overrideSearchTerms: null,
  searchCities: "United Kingdom",
  defaultSearchCities: "United Kingdom",
  overrideSearchCities: null,
  jobspyResultsWanted: 20,
  defaultJobspyResultsWanted: 20,
  overrideJobspyResultsWanted: null,
  jobspyCountryIndeed: "united kingdom",
  defaultJobspyCountryIndeed: "united kingdom",
  overrideJobspyCountryIndeed: null,
  showSponsorInfo: true,
  defaultShowSponsorInfo: true,
  overrideShowSponsorInfo: null,
  chatStyleTone: "professional",
  defaultChatStyleTone: "professional",
  overrideChatStyleTone: null,
  chatStyleFormality: "medium",
  defaultChatStyleFormality: "medium",
  overrideChatStyleFormality: null,
  chatStyleConstraints: "",
  defaultChatStyleConstraints: "",
  overrideChatStyleConstraints: null,
  chatStyleDoNotUse: "",
  defaultChatStyleDoNotUse: "",
  overrideChatStyleDoNotUse: null,
  llmApiKeyHint: null,
  rxresumeEmail: null,
  rxresumePasswordHint: null,
  basicAuthUser: null,
  basicAuthPasswordHint: null,
  ukvisajobsEmail: null,
  ukvisajobsPasswordHint: null,
  adzunaAppId: null,
  adzunaAppKeyHint: null,
  webhookSecretHint: null,
  basicAuthActive: false,
  backupEnabled: false,
  defaultBackupEnabled: false,
  overrideBackupEnabled: null,
  backupHour: 3,
  defaultBackupHour: 3,
  overrideBackupHour: null,
  backupMaxCount: 7,
  defaultBackupMaxCount: 7,
  overrideBackupMaxCount: null,
  penalizeMissingSalary: false,
  defaultPenalizeMissingSalary: false,
  overridePenalizeMissingSalary: null,
  missingSalaryPenalty: 10,
  defaultMissingSalaryPenalty: 10,
  overrideMissingSalaryPenalty: null,
  autoSkipScoreThreshold: null,
  defaultAutoSkipScoreThreshold: null,
  overrideAutoSkipScoreThreshold: null,
  ...overrides,
});
